'use client'

import { useState } from 'react'

const packages = [
  { name: 'The First Week', price: 'A gentle start', detail: 'Small, useful comforts for the first seven days home.', items: ['Cooling eye mask', 'Nourishing body oil', 'First Week Check guide'] },
  { name: 'The Full Reset', price: 'Most loved', detail: 'A fuller rhythm of rest, nourishment, and being looked after.', items: ['Everything in First Week', 'Restorative bath soak', '30-day care plan'] },
  { name: 'A Little Extra', price: 'Add it on', detail: 'A personal finishing touch for a moment that deserves more.', items: ['Ceramic keepsake cup', 'Herbal tea blend', 'A note from you'] },
]

function PackageCard({ item, selected, onSelect }: { item: typeof packages[number]; selected: boolean; onSelect: () => void }) {
  return <article className={`package-card ${selected ? 'is-open' : ''}`}>
    <button className="package-trigger" onClick={onSelect} aria-expanded={selected}><span className="eyebrow">{item.price}</span><span className="package-plus">{selected ? '−' : '+'}</span><h3>{item.name}</h3><p>{item.detail}</p></button>
    {selected && <div className="package-open"><span className="eyebrow">Inside the box</span><ul>{item.items.map((entry) => <li key={entry}>{entry}</li>)}</ul><p className="change-note">Once it&apos;s hers, she can change delivery timing, add a note, or make the care plan her own.</p><button className="text-button" onClick={onSelect}>Close details <span>↗</span></button></div>}
  </article>
}

function GiftFlow() {
  const [step, setStep] = useState(1)
  const [selected, setSelected] = useState(1)
  const labels = ['Choose care', 'Make it personal', 'Delivery', 'Review', 'Send', 'Held']
  return <section className="flow-section" id="gift"><div className="section-kicker"><span>06</span><span>Design-only gift flow</span></div><div className="flow-heading"><div><p className="eyebrow">A gift that keeps showing up</p><h2>Start with care.<br /><em>We&apos;ll handle the rest.</em></h2></div><p className="flow-intro">A mobile-first preview of the six quiet steps between thinking of someone and helping them feel held.</p></div><div className="flow-shell"><div className="flow-progress">{labels.map((label, index) => <div className={`flow-step ${step >= index + 1 ? 'is-active' : ''}`} key={label}><span>{String(index + 1).padStart(2, '0')}</span><small>{label}</small></div>)}</div><div className="flow-content"><p className="eyebrow">Step {step} of 6</p><h3>{['Choose what feels right.', 'Add the thoughtful details.', 'Pick a gentle arrival.', 'See the care before it goes.', 'A final note from you.', 'Your gift is on its way.'][step - 1]}</h3><p className="flow-copy">{['Packages are designed around the real rhythms of early recovery.', 'A name, a note, and an occasion are all we need to make it personal.', 'Choose now, later, or leave the timing open for her.', 'A clean, calm summary before anything is sent.', 'One small message can carry a lot of care.', 'The final screen is a soft landing, not a sales receipt.'][step - 1]}</p>{step === 1 && <div className="flow-options">{packages.map((item, index) => <PackageCard key={item.name} item={item} selected={selected === index} onSelect={() => setSelected(index)} />)}</div>}{step > 1 && <div className="flow-preview"><span className="preview-line" /><span className="preview-line short" /><span className="preview-line" /></div>}<div className="flow-actions">{step > 1 && <button className="light-button" onClick={() => setStep(step - 1)}>Back</button>}<button className="dark-button" onClick={() => setStep(step === 6 ? 1 : step + 1)}>{step === 6 ? 'Start again' : 'Continue'} <span>→</span></button></div></div></div><p className="desktop-note">On desktop, the flow sits in a wide split panel. On phone, it becomes one focused card with the step rail kept visible.</p></section>
}

function AppSections() {
  const [openFrame, setOpenFrame] = useState(0)
  const frames = [['01', 'A message arrives', 'A quiet notification lands: “Someone sent care.”'], ['02', 'Small things resolve', 'A warm drink appears. A delivery timing changes. The list gets lighter.'], ['03', 'Weight lifts', 'The screen clears to one simple feeling: you are not doing this alone.']]
  return <>
    <section className="storyboard-section" id="story"><div className="section-kicker"><span>01</span><span>Hero motion direction</span></div><div className="storyboard-head"><div><p className="eyebrow">A short film, not a sales pitch</p><h2>Care arrives<br /><em>in little ways.</em></h2></div><p>Storyboard direction for a 12-second hero loop. No busy animation: just the feeling of a message arriving, small tasks resolving around her, and the weight of the day lifting.</p></div><div className="frames">{frames.map(([number, title, copy], index) => <button className={`frame ${openFrame === index ? 'is-selected' : ''}`} key={number} onClick={() => setOpenFrame(index)}><span className="frame-number">{number}</span><span className="frame-scene"><span className="scene-orbit" /></span><strong>{title}</strong><small>{copy}</small></button>)}</div><p className="motion-note"><strong>Motion:</strong> 400ms ease-out message slide-in → 700ms staggered object settles → 1.2s slow camera pull-back. End on a 2s breathing hold. Keep sound optional and captions on.</p></section>
    <section className="trust-section" id="trust"><div className="section-kicker"><span>02</span><span>Data forward, by choice</span></div><div className="trust-grid"><div><p className="eyebrow">Information should feel like care</p><h2>She chooses<br /><em>what we know.</em></h2></div><div className="trust-copy"><p>Morrow only asks for the details that make support more useful: how she is feeling, what sounds good, and when a check-in might help.</p><div className="trust-list"><div><span>01</span><p><strong>Clear by default</strong><br />Every question explains why it is here.</p></div><div><span>02</span><p><strong>Useful, never invasive</strong><br />Her answers shape recommendations, not assumptions.</p></div><div><span>03</span><p><strong>Always hers</strong><br />She can edit, skip, or remove her information at any time.</p></div></div></div></div></section>
    <section className="balance-section" id="balance"><div className="balance-copy"><p className="eyebrow">03 / The care balance</p><h2>Her circle<br /><em>makes room.</em></h2><p>Friends and family contribute to one shared gift. That support turns into real things she can feel: a meal, a quiet hour, a care box, a check-in when the week gets full.</p><a className="underlined-link" href="#gift">See the gift flow <span>↗</span></a></div><div className="balance-objects"><div><strong>01</strong><span>Warm food</span><i>●</i></div><div><strong>02</strong><span>Restful care</span><i>◐</i></div><div><strong>03</strong><span>Human support</span><i>○</i></div></div></section>
    <section className="packages-section" id="packages"><div className="section-kicker"><span>04</span><span>Quiet packages</span></div><div className="packages-heading"><div><p className="eyebrow">Nothing extra, everything considered</p><h2>Open the box.<br /><em>Keep the choice.</em></h2></div><p>Tap a card to see the reusable open state. Once it&apos;s hers, the care can keep adapting.</p></div><div className="package-grid">{packages.map((item, index) => <PackageCard key={item.name} item={item} selected={index === 1} onSelect={() => {}} />)}</div></section>
    <section className="video-section" id="film"><div className="section-kicker"><span>05</span><span>Watch when there&apos;s room</span></div><div className="video-heading"><div><p className="eyebrow">A film for the beginning</p><h2>Let the day<br /><em>be gentle.</em></h2></div><p>A live-source video treatment with a soft poster fallback, captions, controls, and no autoplay.</p></div><div className="video-frame"><video controls preload="metadata" poster="/images/morrow-ritual.png" aria-label="A quiet film about making room for rest"><source src="https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4" type="video/mp4" />Your browser does not support the video element.</video><div className="video-note">morrow / a quiet film</div></div></section>
    <section className="numbers-section"><div className="section-kicker"><span>07</span><span>Why it matters</span></div><div className="numbers-grid"><div><strong>1 in 5</strong><p>new parents experience postpartum mood symptoms.</p></div><div><strong>6 weeks</strong><p>is only the traditional check-in. Care continues long after.</p></div><div><strong>100%</strong><p>of parents deserve practical, unhurried support.</p></div></div></section>
  </>
}

export default function Page() { return <main><nav className="site-nav"><a className="wordmark" href="#top">morrow<span>·</span></a><div className="nav-links"><a href="#trust">Trust</a><a href="#packages">Packages</a><a href="/first-week-check">First Week Check</a></div><a className="nav-cta" href="#gift">Send a gift <span>↗</span></a></nav><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Care, made visible</p><h1>For the ones<br /><em>who held you.</em></h1><p className="hero-sub">Postpartum care, thoughtfully gathered and gently delivered. Because the person who made the beginning possible deserves a beginning of their own.</p><a className="dark-button" href="#gift">Give them morrow <span>→</span></a><p className="hero-note">✦ Designed with midwives, doulas &amp; new parents</p></div><div className="hero-art"><img src="/images/morrow-hero.png" alt="Morrow care box with tea and folded linen" /><div className="hero-label">a softer<br /><em>way forward</em></div><div className="hero-caption">00 / A considered start</div></div></section><div className="marquee"><span>Rest is productive</span><i>✦</i><span>Care is a practice</span><i>✦</i><span>Small things matter</span></div><section className="manifesto"><div className="section-kicker"><span>08</span><span>The why</span></div><div className="manifesto-grid"><h2>The fourth trimester<br />is a <em>new beginning.</em></h2><div className="manifesto-copy"><p>We prepare endlessly for the arrival of a baby. But what about the person who made it all possible?</p><p>Morrow is a reminder that care should not stop at the threshold of birth.</p></div></div></section><AppSections /><GiftFlow /><section className="closing-section"><div><p className="eyebrow">For every beginning</p><h2>Give care<br /><em>forward.</em></h2></div><a className="dark-button" href="#gift">Send a morrow gift <span>↗</span></a></section><footer className="site-footer"><div className="footer-mark">morrow<span>·</span></div><p>Care for the beginning<br />and everything after.</p><div className="footer-links"><a href="#trust">Trust</a><a href="/first-week-check">First Week Check</a><a href="#gift">Contact</a></div><small>© 2026 morrow care co. · Designed and developed by Afaq Ahmad</small></footer></main> }

export { packages }

// The six-step flow is intentionally a visual prototype; no checkout is connected.
// Package detail cards share one open state pattern across the page.
